### ISSUE TITLE
Inquiry Regarding Model Training Code for Reproducing Paper Results

### ISSUE THREAD

**Issue by a2108870** [MarcoBauzz/convolutional-color-constancy#1]
Hi
Thank you for sharing your work and for providing valuable resources in this repository. I understand from the documentation that the training code has not been officially released. However, I wanted to ask if the model training code available in cfcc.py could be used to reproduce the results presented in your paper.

**Comment by MarcoBauzz** [comment]
Hi,
yes, the code in cfcc.py already contains all necessary functions to correctly train our models from the paper.
We will be gradually updating the repository to include example runs and trained models.
